// Code generated by sqlc. DO NOT EDIT.

package weather

import (
	"time"
)

type User struct {
	ID          int64
	Name        string
	Zipcode     string
	Location    string
	Temperature float64
	FeelsLike   float64
	CreatedAt   time.Time
}
