// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package weather

import (
	"context"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO "user" (
  name,zipcode,location,temperature,feels_like
) VALUES (
  $1, $2 , $3, $4, $5
)
RETURNING id, name, zipcode, location, temperature, feels_like, created_at
`

type CreateRecordParams struct {
	Name        string
	Zipcode     string
	Location    string
	Temperature float64
	FeelsLike   float64
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createRecord,
		arg.Name,
		arg.Zipcode,
		arg.Location,
		arg.Temperature,
		arg.FeelsLike,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Zipcode,
		&i.Location,
		&i.Temperature,
		&i.FeelsLike,
		&i.CreatedAt,
	)
	return i, err
}
