// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type User struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Zipcode     string    `json:"zipcode"`
	Location    string    `json:"location"`
	Temperature float64   `json:"temperature"`
	FeelsLike   float64   `json:"feels_like"`
	CreatedAt   time.Time `json:"created_at"`
}
